spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hariyalidbletest?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    show-sql: true
  main:
       lazy-initialization: true
  servlet:
          multipart:
             max-file-size : 5MB
             max-request-size : 5MB

#  mail:
#    host : smtp.gmail.com
#    port : 587
#    username : nayandandwate55@gmail.com
#    password : hxiiyngadcoxqefa
#    properties :
#      mail :
#        smtp :
#          auth : true
#          starttls :
#            enable : true
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: ${JPA_HIBERNATE_FORMAT_SQL:false}
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
 
#  logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE      
  logging:
  level:
    hariyali: ${LOGGIN_LEVEL_APP:INFO}
    org:
      hibernate:
        sql : ${LOGGIN_LEVEL_APP:DEBUG}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

#lock time will be in minuits   
user:
    account:
            locktime: 3
            
jwt:
   secret : boooooooooom!!!!
#   Time in Hours
   expireTime : 8
# change this url as deployed environment
frontend:
        # redirect-url: http://localhost:3000/OnlineDonation?orderId=
        redirect-url: https://hariyali-dev.m-devsecops.com/OnlineDonation?orderId=
        redirect-gogreen-url: https://hariyali-dev.m-devsecops.com/OnlineDonation
receipt:
        receiptPath: classpath:DonationReceipt/        
   
   
request:
        rate:
            limit: 500
            noOfMinute: 1
# change this path as per environment
log:
    path: c:/log
#cc_service credentials
cc_service: 
          APP_ID: caf3ebf3-67c0-43f3-ad1a-7d5d3437d760
          CC_BASE_URL: https://ccservice-dev.m-devsecops.com/
encryption:
           key: emgut@kL9RQ%L#tt        